FROM node:22-alpine
WORKDIR /app
COPY package.json package-lock.json tsconfig.base.json ./
COPY packages/db ./packages/db
RUN npm install --workspace=@supadupabase/db --include=dev -w @supadupabase/db
CMD ["npm", "run", "migrate", "-w", "@supadupabase/db"]
